

class Urls:
    BASE_URL = "https://hppat.bintime.com"
    LOGIN_PAGE = f'{BASE_URL}/login'
    MAIN_PAGE = f'{BASE_URL}/import/request'
    TEMPLATES_MANAGEMENT_ = f'{BASE_URL}/import/template'
    PARTNERS_MANAGEMENT = f'{BASE_URL}/partners/partners'
    USERS_MANAGEMENT = f'{BASE_URL}/user/user'
    RESET_PASSWORD = f'{BASE_URL}/reset-password-request'
    USER_CREATE_PAGE = f'{BASE_URL}/user/user/create'
    TEMP_MAIL = 'https://temp-mail.io/en/'


class Creds:
    LOGIN = 'bintime.yemets@gmail.com'
    PASSWORD = r'' #type in the password here
    SAMPLE_USER_EMAIL = 'sample@email.com'
    TEMP_MAIL = ''


class TextMainPage:
    MAIN_LOGO = 'HP Partner Automation Tool'
    MENU_DROPDOWN_MAIN = 'Menu'
    MENU_TEMPLATES_MGMT = 'Templates Management'
    MENU_PARTNERS_MGMT = 'Partners Management'
    MENU_USERS_MGMT = 'Users Management'
    MENU_SETUP_SHEET = 'Set-Up Sheet Requests'
    LOGOUT_BTN = 'Logout'
    COUNTRY_SEARCH = 'Country'
    COUNTRY_SEARCH_DROPDOWN = 'Country dropdown'
    PARTNER_SEARCH = 'Partner Name'
    PARTNER_SEARCH_FIELD = 'Partner Name Field'
    CATEGORY_SEARCH = 'Category'
    CATEGORY_SEARCH_FIELD = 'Category Field'
    GENERATED_BY_SEARCH = 'Generated By'
    GENERATED_BY_DROPDOWN = 'Generated By Dropdown'
    SEARCH_BTN = 'Search'
    CLEAR_BTN = 'Clear'
    GENERATE_BTN = 'Generate Sheet and Media'
    COLUMNS_DROPDOWN = 'Columns'
    ITEMS_PER_PAGE_DEFAULT = '20 items per page'

class AssertionText:
    ELEM = 'Element '
    PRESENT = ' is presented'
    NOT_PRESENTED = ' is not presented'
    TEXT_IN_ELEM = 'Text in the element'

class TelegramBot:
    HPATBOT = 'https://api.telegram.org/bot1592884711:AAGh9IooYd4P0VO-QfwhouhfxxEMnehbqzo/sendMessage'
    TESTCHATID = ('chat_id', '-1001392266966')