

class Urls:
    LOGIN_PAGE = 'https://test-hppat.bintime.com/login'
    MAIN_PAGE = 'https://test-hppat.bintime.com/import/request'
    TEMPLATES_MANAGEMENT_ = 'https://test-hppat.bintime.com/import/template'
    PARTNERS_MANAGEMENT = 'https://test-hppat.bintime.com/partners/partners'
    USERS_MANAGEMENT = 'https://test-hppat.bintime.com/user/user'
    RESET_PASSWORD = 'https://test-hppat.bintime.com/reset-password-request'


class Creds:
    ADMIN_LOGIN = 'bintime@bintime.com'
    ADMIN_PASSWORD = r'n]\56ff-D9vK*GVU'
    SAMPLE_USER_EMAIL = 'sample@email.com'


class TextMainPage:
    MAIN_LOGO = 'HP Partner Automation Tool'
    MENU_DROPDOWN_MAIN = 'Menu'
    MENU_TEMPLATES_MGMT = 'Templates Management'
    MENU_PARTNERS_MGMT = 'Partners Management'
    MENU_USERS_MGMT = 'Users Management'
    MENU_SETUP_SHEET = 'Set-Up Sheet Requests'
    LOGOUT_BTN = 'Logout'
    COUNTRY_SEARCH = 'Country'
    COUNTRY_SEARCH_DROPDOWN = 'Country dropdown'
    PARTNER_SEARCH = 'Partner Name'
    PARTNER_SEARCH_FIELD = 'Partner Name Field'
    CATEGORY_SEARCH = 'Category'
    CATEGORY_SEARCH_FIELD = 'Category Field'
    GENERATED_BY_SEARCH = 'Generated By'
    GENERATED_BY_DROPDOWN = 'Generated By Dropdown'
    SEARCH_BTN = 'Search'
    CLEAR_BTN = 'Clear'
    GENERATE_BTN = 'Generate Sheet and Media'
    COLUMNS_DROPDOWN = 'Columns'
    ITEMS_PER_PAGE_DEFAULT = '20 items per page'

class AssertionText:
    ELEM = 'Element '
    PRESENT = ' is presented'
    NOT_PRESENTED = ' is not presented'
    TEXT_IN_ELEM = 'Text in the element'

class TelegramBot:
    HPATBOT = 'https://api.telegram.org/bot1592884711:AAGh9IooYd4P0VO-QfwhouhfxxEMnehbqzo/sendMessage'
    TESTCHATID = ('chat_id', '-1001392266966')